name: Build AppImage

on:
  push:

jobs:
  linux:
    name: AppImage
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: '6.9.*'
          cache: true

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build
        run: |
          mkdir build && cd build
          cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_CXX_COMPILER=clang++ ..
          cmake --build . --config RelWithDebInfo -j $(nproc)
          cd ..

      - name: Install LinuxDeploy
        uses: miurahr/install-linuxdeploy-action@v1
        with:
          plugins: qt appimage
          dir: ${{ github.workspace }}

      - name: Install FUSE
        run: |
          sudo apt-add-repository universe
          sudo apt install libfuse2 -y

      - name: Build release package
        run: |
          linuxdeploy-x86_64.AppImage --plugin qt --output appimage --desktop-file dev.lorendb.kaon.desktop --icon-file icons/kaon.svg --executable build/src/kaon --appdir AppDir

      - name: Upload release package
        uses: actions/upload-artifact@v2
        with:
          name: AppImage
          path: kaon-*-x86_64.AppImage
          retention-days: 7
